apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-api-config
  namespace: ecommerce
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  PUBLIC_HOST: "https://api.example.com"
  PORT: "8080"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_NAME: "ecom"
  JWT_EXPIRATION_IN_SECONDS: "604800"
